_target_: utils.train_DL_model
model: ??
early_stop_threshold: 0.95
early_stop_n_epoch: 15
n_epoch: 200
log_wandb: True
optimizer:
  _target_: utils.get_partial_optimizer
  optimizer_name: "AdamW"
  lr: ${model_config.learning_rate}
  weight_decay: ${model_config.weight_decay}
criterion:
  _target_: torch.nn.L1Loss
train_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset: ??
  batch_size: ${model_config.batch_size}
  shuffle: True
  num_workers: 4
validation_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset: ??
  batch_size: ${model_config.batch_size}
  shuffle: False
  num_workers: 4
phenotype: ??
display_evolution_threshold: 0.5
scheduler:
  _target_: utils.get_partial_scheduler
  scheduler_name: "LinearLR"
  total_iters: 20
  start_factor: 1e-3