config:
  hidden_size: 2048
  batch_size: 16
  learning_rate: 8.89e-4
  dropout: 0.2

train_function:
  _target_: utils.train_DL_model
  model:
    _target_: MLP.MLP
    dropout: ${template.config.dropout}
    nlayers: 10
    hidden_nodes: 
      - ${template.config.hidden_size}
      - ${template.config.hidden_size}
      - ${template.config.hidden_size}
      - ${template.config.hidden_size}
      - ${div:${mul:${template.config.hidden_size},3},4} 
      - ${div:${template.config.hidden_size},2}
      - ${div:${template.config.hidden_size},2}
      - ${div:${template.config.hidden_size},2}
      - ${div:${template.config.hidden_size},2}
  early_stop_threshold: 0.95
  early_stop_n_epoch: 15
  n_epoch: 200
  log_wandb: False
  optimizer:
    _target_: utils.get_partial_optimizer
    optimizer_name: "Adam"
    lr: ${template.config.learning_rate}
  criterion:
    _target_: torch.nn.L1Loss
  train_dataloader: ??
  validation_dataloader: ??
  phenotype: ??