name: "Deep_MLP ?? full hyperparameter tuning"
method: random
metric: 
  goal: maximize
  name: "correlation ??.max"
parameters:
  learning_rate: 
      # np.linspace(1e-3,1e-6,10)
      values: [1.00e-03, 8.89e-04, 7.78e-04, 6.67e-04, 5.56e-04, 4.45e-04, 3.34e-04, 2.23e-04, 1.12e-04, 1.00e-06]
  #list(map(lambda v: 2**v, range(5,13))
  hidden_size: 
      values: [32, 64, 128, 256, 512, 1024, 2048, 4096]
  #np.arange(0.05,0.55,0.05)
  dropout: 
      values: [0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ]
  #list(map(lambda v: 2**v, range(3,9))
  batch_size: 
      values: [8, 16, 32, 64, 128, 256, 512]
run_cap: 40


