name: "LCLNN ?? full hyperparameter tuning"
method: bayes
metric: 
  goal: maximize
  name: "correlation ??.max"
parameters:
  learning_rate: 
      values: [1e-03, 5e-3, 1e-4, 5e-4, 1e-5]
  hidden_size_0: 
      values: [64, 128, 256, 512, 1024, 2048]
  hidden_size_1: 
      values: [0, 2, 4, 8, 16, 32, 64]
  dropout:
      values: [0, 0.1, 0.2, 0.3, 0.4, 0.5]
run_cap: 30