name: "ResGS hyperparameter search"
method: bayes
metric: 
  goal: maximize
  name: "correlation ??.max"
parameters:
  learning_rate: 
    distribution: log_uniform
    min: -11.512925464970229 # log(1e-5)
    max: -2.3025850929940455 # log(0-1)
  weight_decay:
    distribution: log_uniform
    min: -11.512925464970229 # log(1e-5)
    max: 2.302585092994046 # log(10)
      
run_cap: 40


