hidden_size: 1024
batch_size: 256
learning_rate: 1e-3
dropout: 0.25

model:
  _target_: Models.MLP.MLP
  dropout: ${model_config.dropout}
  nlayers: 10
  hidden_nodes: 
    - ${model_config.hidden_size}
    - ${model_config.hidden_size}
    - ${model_config.hidden_size}
    - ${model_config.hidden_size}
    - ${div:${mul:${model_config.hidden_size},3},4} 
    - ${div:${model_config.hidden_size},2}
    - ${div:${model_config.hidden_size},2}
    - ${div:${model_config.hidden_size},2}
    - ${div:${model_config.hidden_size},2}