batch_size : 32
learning_rate : 5e-4
# must be divisble by n_heads !!
n_embedding : 48
n_heads : 4
n_blocks : 4
n_hidden : 1024
mutual_info_threshold : 0.02
model:
  _target_: Models.GPTransformer.GPTransformer
  n_features: ??
  embedding_size: ${model_config.n_embedding}
  n_hidden: ${model_config.n_hidden}
  n_heads: ${model_config.n_heads}
  n_blocks: ${model_config.n_blocks}
  embedding_type: ??
  embedding_table_weight: ??