batch_size : 8
learning_rate : 1e-5
n_embedding : 8
n_heads : 2
n_blocks : 2
n_hidden : 256
mutual_info_threshold : 0.03
model:
  _target_: Models.GPTransformer.GPTransformer
  n_features: ??
  embedding_size: ${model_config.n_embedding}
  n_hidden: ${model_config.n_hidden}
  n_heads: ${model_config.n_heads}
  n_blocks: ${model_config.n_blocks}