batch_size: 256
learning_rate: 1e-4
num_snp: 36304
dropout: 0
mlp_hidden_size: 1024
model:
  _target_: Models.LCLNN.LCLNN
  num_snp: ${model_config.num_snp}
  mlp_hidden_size: ${model_config.mlp_hidden_size}
  dropout: ${model_config.dropout}