batch_size: 64
learning_rate: 1e-3
dropout: 0
n_layers: 11
kernel_size: 3
channel_factor1: 4
channel_factor2: 1.1
n_filters: 64
weight_decay: 1.0
model:
  _target_: Models.ResGS.ResGSModel
  nFilter: ${model_config.n_filters}
  _KERNEL_SIZE: ${model_config.kernel_size}
  CHANNEL_FACTOR1: ${model_config.channel_factor1}
  CHANNEL_FACTOR2: ${model_config.channel_factor2}
  nlayers: ${model_config.n_layers}