learning_rate: 1e-4
batch_size: 64
start_channel_size: 64
kernel_size: 3
layers_size:
  - 2
  - 2
  - 2
  - 2
regressor_hidden_size:
  - 128
aggregation: "strided_LCL"
weight_decay: 1e-4
model:
  _target_: Models.ResNet.ResNet
  start_channel_size: ${model_config.start_channel_size}
  kernel_size: ${model_config.kernel_size}
  layers_size: ${model_config.layers_size}
  regressor_hidden_size: ${model_config.regressor_hidden_size}
  aggregation: ${model_config.aggregation}