hidden_size: 512
batch_size: 32
learning_rate: 0.000556
dropout: 0.15

model:
  _target_: Models.MLP.MLP
  dropout: ${model_config.dropout}
  nlayers: 2
  hidden_nodes: 
    - ${model_config.hidden_size}