batch_size: 256
learning_rate: 0.00001
num_snp: 36304
dropout: 0.4
hidden_size_0: 2048
hidden_size_1: 64
model:  
  _target_: Models.LCLNN.LCLNN
  num_snp: ${model_config.num_snp}
  mlp_hidden_size: 
    - ${model_config.hidden_size_0}
    - ${model_config.hidden_size_1}
  dropout: ${model_config.dropout}