hidden_size: 10240
batch_size: 1024
learning_rate: 0.005
dropout: 0.5

model:
  _target_: Models.MLP.MLP
  dropout: ${model_config.dropout}
  nlayers: 2
  hidden_nodes: 
    - ${model_config.hidden_size}